### ISSUE TITLE
Implement map to set latitude/longitude

### ISSUE THREAD

**Issue by matiboy** [vnealv/kinetic#4]
On entry of Site, have a map (no preference but Google map should work well) with a pin representing the site. Move the pin or double click on the map to set position; reflects on the lat/long input fields.

Similarly, changing the value on the input fields should change the map pin.

Any JS framework can be used, or vanilla JS, anything goes

**Comment by vnealv** [comment]
@matiboy ok issue 4 is done now. Thank you for the interesting issues
